package eu.kanade.tachiyomi.ui.stats.achievements

import eu.kanade.presentation.more.stats.data.Achievement
import eu.kanade.presentation.more.stats.data.AchievementCategory
import eu.kanade.presentation.more.stats.data.AchievementTier
import eu.kanade.presentation.more.stats.data.AchievementsSummary

object AchievementsEngine {

    fun compute(
        currentStreakDays: Int,
        bestStreakDays: Int,
        totalAnimeWatchTimeMs: Long,
        totalMangaReadTimeMs: Long,
        episodesWatched: Int,
        chaptersRead: Int,
        completedAnimeCount: Int,
        completedMangaCount: Int,
        nightSessionsCount: Int,
        morningSessionsCount: Int,
        topGenreCount: Int,
    ): AchievementsSummary {
        val watchHours = totalAnimeWatchTimeMs / (1000L * 60 * 60)
        val readHours = totalMangaReadTimeMs / (1000L * 60 * 60)
        val totalCompleted = (completedAnimeCount + completedMangaCount).toLong()
        val maxStreak = maxOf(currentStreakDays, bestStreakDays).toLong()

        val list = listOf(
            // ── STREAKS ───────────────────────────────────────────────
            Achievement(
                id = "streak_3",
                title = "Spark",
                description = "Maintain an active streak for 3 days",
                category = AchievementCategory.STREAKS,
                tier = AchievementTier.BRONZE,
                emoji = "🔥",
                currentValue = maxStreak,
                targetValue = 3L,
                unit = "days",
            ),
            Achievement(
                id = "streak_7",
                title = "Habit Former",
                description = "Maintain an active streak for 7 days",
                category = AchievementCategory.STREAKS,
                tier = AchievementTier.SILVER,
                emoji = "⚡",
                currentValue = maxStreak,
                targetValue = 7L,
                unit = "days",
            ),
            Achievement(
                id = "streak_14",
                title = "Dedicated Otaku",
                description = "Keep your streak going strong for 14 days",
                category = AchievementCategory.STREAKS,
                tier = AchievementTier.GOLD,
                emoji = "🌟",
                currentValue = maxStreak,
                targetValue = 14L,
                unit = "days",
            ),
            Achievement(
                id = "streak_30",
                title = "Monthly Master",
                description = "Reach an incredible 30-day streak",
                category = AchievementCategory.STREAKS,
                tier = AchievementTier.PLATINUM,
                emoji = "🏆",
                currentValue = maxStreak,
                targetValue = 30L,
                unit = "days",
            ),
            Achievement(
                id = "streak_100",
                title = "Legendary Devotion",
                description = "Attain an elite 100-day reading & watching streak",
                category = AchievementCategory.STREAKS,
                tier = AchievementTier.DIAMOND,
                emoji = "👑",
                currentValue = maxStreak,
                targetValue = 100L,
                unit = "days",
            ),

            // ── ANIME WATCH TIME ──────────────────────────────────────
            Achievement(
                id = "watch_10",
                title = "Anime Explorer",
                description = "Watch 10 hours of anime",
                category = AchievementCategory.ANIME_TIME,
                tier = AchievementTier.BRONZE,
                emoji = "🍿",
                currentValue = watchHours,
                targetValue = 10L,
                unit = "hours",
            ),
            Achievement(
                id = "watch_50",
                title = "Seasoned Binger",
                description = "Watch 50 hours of anime",
                category = AchievementCategory.ANIME_TIME,
                tier = AchievementTier.SILVER,
                emoji = "🎬",
                currentValue = watchHours,
                targetValue = 50L,
                unit = "hours",
            ),
            Achievement(
                id = "watch_100",
                title = "Centurion Viewer",
                description = "Watch 100 hours of anime",
                category = AchievementCategory.ANIME_TIME,
                tier = AchievementTier.GOLD,
                emoji = "🎭",
                currentValue = watchHours,
                targetValue = 100L,
                unit = "hours",
            ),
            Achievement(
                id = "watch_250",
                title = "Anime Connoisseur",
                description = "Watch 250 hours of anime",
                category = AchievementCategory.ANIME_TIME,
                tier = AchievementTier.PLATINUM,
                emoji = "📽️",
                currentValue = watchHours,
                targetValue = 250L,
                unit = "hours",
            ),
            Achievement(
                id = "watch_500",
                title = "Grand Anime Sage",
                description = "Watch 500 hours of anime",
                category = AchievementCategory.ANIME_TIME,
                tier = AchievementTier.DIAMOND,
                emoji = "🔮",
                currentValue = watchHours,
                targetValue = 500L,
                unit = "hours",
            ),

            // ── MANGA READ TIME ───────────────────────────────────────
            Achievement(
                id = "read_10",
                title = "Page Turner",
                description = "Read 10 hours of manga",
                category = AchievementCategory.MANGA_TIME,
                tier = AchievementTier.BRONZE,
                emoji = "📖",
                currentValue = readHours,
                targetValue = 10L,
                unit = "hours",
            ),
            Achievement(
                id = "read_50",
                title = "Avid Bookworm",
                description = "Read 50 hours of manga",
                category = AchievementCategory.MANGA_TIME,
                tier = AchievementTier.SILVER,
                emoji = "📚",
                currentValue = readHours,
                targetValue = 50L,
                unit = "hours",
            ),
            Achievement(
                id = "read_100",
                title = "Manga Scholar",
                description = "Read 100 hours of manga",
                category = AchievementCategory.MANGA_TIME,
                tier = AchievementTier.GOLD,
                emoji = "📜",
                currentValue = readHours,
                targetValue = 100L,
                unit = "hours",
            ),
            Achievement(
                id = "read_250",
                title = "Grand Archivist",
                description = "Read 250 hours of manga",
                category = AchievementCategory.MANGA_TIME,
                tier = AchievementTier.PLATINUM,
                emoji = "🏛️",
                currentValue = readHours,
                targetValue = 250L,
                unit = "hours",
            ),
            Achievement(
                id = "read_500",
                title = "Supreme Reader",
                description = "Read 500 hours of manga",
                category = AchievementCategory.MANGA_TIME,
                tier = AchievementTier.DIAMOND,
                emoji = "🌌",
                currentValue = readHours,
                targetValue = 500L,
                unit = "hours",
            ),

            // ── VOLUME & COMPLETIONS ──────────────────────────────────
            Achievement(
                id = "episodes_50",
                title = "Episode Initiate",
                description = "Watch 50 episodes",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.BRONZE,
                emoji = "📺",
                currentValue = episodesWatched.toLong(),
                targetValue = 50L,
                unit = "episodes",
            ),
            Achievement(
                id = "chapters_100",
                title = "Chapter Voyager",
                description = "Read 100 chapters",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.BRONZE,
                emoji = "📑",
                currentValue = chaptersRead.toLong(),
                targetValue = 100L,
                unit = "chapters",
            ),
            Achievement(
                id = "episodes_250",
                title = "Episode Veteran",
                description = "Watch 250 episodes",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.SILVER,
                emoji = "🎞️",
                currentValue = episodesWatched.toLong(),
                targetValue = 250L,
                unit = "episodes",
            ),
            Achievement(
                id = "chapters_500",
                title = "Library Champion",
                description = "Read 500 chapters",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.GOLD,
                emoji = "📗",
                currentValue = chaptersRead.toLong(),
                targetValue = 500L,
                unit = "chapters",
            ),
            Achievement(
                id = "chapters_1000",
                title = "Thousand Chapters Club",
                description = "Read 1,000 chapters across your manga",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.PLATINUM,
                emoji = "💎",
                currentValue = chaptersRead.toLong(),
                targetValue = 1000L,
                unit = "chapters",
            ),
            Achievement(
                id = "completed_10",
                title = "Series Finisher",
                description = "Complete 10 anime or manga series",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.GOLD,
                emoji = "🏁",
                currentValue = totalCompleted,
                targetValue = 10L,
                unit = "series",
            ),
            Achievement(
                id = "completed_25",
                title = "The Completionist",
                description = "Complete 25 anime or manga series",
                category = AchievementCategory.VOLUME,
                tier = AchievementTier.DIAMOND,
                emoji = "🎖️",
                currentValue = totalCompleted,
                targetValue = 25L,
                unit = "series",
            ),

            // ── HABITS & SPECIAL ──────────────────────────────────────
            Achievement(
                id = "habit_night_owl",
                title = "Creature of the Night",
                description = "Log 10 reading/watching sessions between 10 PM and 5 AM",
                category = AchievementCategory.HABITS,
                tier = AchievementTier.SILVER,
                emoji = "🦉",
                currentValue = nightSessionsCount.toLong(),
                targetValue = 10L,
                unit = "sessions",
            ),
            Achievement(
                id = "habit_early_bird",
                title = "Dawn Explorer",
                description = "Log 10 reading/watching sessions between 5 AM and 11 AM",
                category = AchievementCategory.HABITS,
                tier = AchievementTier.SILVER,
                emoji = "🌅",
                currentValue = morningSessionsCount.toLong(),
                targetValue = 10L,
                unit = "sessions",
            ),
            Achievement(
                id = "genre_specialist",
                title = "Genre Devotee",
                description = "Have 20+ titles in your top favorite genre",
                category = AchievementCategory.HABITS,
                tier = AchievementTier.GOLD,
                emoji = "🎨",
                currentValue = topGenreCount.toLong(),
                targetValue = 20L,
                unit = "titles",
            ),
        )

        val unlocked = list.filter { it.isUnlocked }
        val locked = list.filterNot { it.isUnlocked }.sortedByDescending { it.progress }
        val percentage = if (list.isEmpty()) 0f else unlocked.size.toFloat() / list.size

        return AchievementsSummary(
            totalUnlocked = unlocked.size,
            totalAchievements = list.size,
            completionPercentage = percentage,
            allAchievements = list,
            recentUnlocked = unlocked.takeLast(4).reversed(),
            nextToUnlock = locked.take(4),
        )
    }
}
